Repository accredible/accredible-learndash-add-on, pull requests merged in 2022-04, with the labels that each got.

#28 NTGR-611 | Use composer v1 for older PHP versions
  .github/workflows/ci.yml
Labels: reviewed

#29 NTGR-615: Add icon and banner images
  assets/banner-1544x500.png
  assets/banner-1800x690.png
  assets/banner-772x250.png
  assets/icon-128x128.png
  assets/icon-256x256.png
Labels: waiting-review

#31 Release: Bump version to 1.0.2
  .github/workflows/ci.yml
  accredible-learndash-add-on.php
  assets/banner-1544x500.png
  assets/banner-1800x690.png
  assets/banner-772x250.png
  assets/icon-128x128.png
  assets/icon-256x256.png
  readme.txt
Labels: reviewed

#32 NTGR-578 - added issuer info in settings page
  assets/css/accredible-admin-settings.css
  assets/images/credits.png
  includes/helpers/class-accredible-learndash-admin-form-helper.php
  includes/templates/admin-settings.php
Labels: reviewed

#30 NTGR-600 - add confirmation dialog
  accredible-learndash-add-on.php
  assets/css/accredible-admin-settings.css
  assets/js/accredible-dialog.js
  includes/class-accredible-learndash-admin-scripts.php
  includes/helpers/class-accredible-learndash-admin-table-helper.php
Labels: reviewed

#33 NTGR-618: Add svnignore
  .svnignore
Labels: reviewed

#37 Release: Bump to version 1.0.3
  .phpcs.xml.dist
  .svnignore
  accredible-learndash-add-on.php
  assets/css/accredible-admin-settings.css
  assets/images/credits.png
  assets/js/accredible-dialog.js
  includes/class-accredible-learndash-admin-scripts.php
  includes/helpers/class-accredible-learndash-admin-form-helper.php
  includes/helpers/class-accredible-learndash-admin-table-helper.php
  includes/templates/admin-settings.php
  index.php
  readme.txt
Labels: reviewed

#36 NTGR-588: Improve auto issuance list performance with group search
  includes/helpers/class-accredible-learndash-admin-table-helper.php
  includes/rest-api/v1/class-accredible-learndash-api-v1-client.php
  tests/includes/rest-api/v1/test-class-accredible-learndash-api-v1-client.php
Labels: reviewed

#38 NTGR-601 - add toasts
  assets/css/accredible-admin-settings.css
  assets/images/close.svg
  assets/js/accredible-common.js
  assets/js/accredible-dialog.js
  assets/js/accredible-toast.js
  includes/ajax/class-accredible-learndash-ajax.php
  includes/class-accredible-learndash-admin-scripts.php
  includes/class-accredible-learndash-admin.php
  includes/helpers/class-accredible-learndash-issuer-helper.php
  includes/templates/admin-settings.php
  tests/includes/test-class-accredible-learndash-admin-scripts.php
  tests/includes/test-class-accredible-learndash-admin.php
Labels: reviewed, waiting-review

#35 NTGR-599: Add validations to AutoIssuance
  bin/init-wp-dev.sh
  includes/class-accredible-learndash-admin-action-handler.php
  includes/models/class-accredible-learndash-model-auto-issuance.php
  includes/models/class-accredible-learndash-model.php
  tests/includes/models/test-class-accredible-learndash-model-auto-issuance.php
  tests/includes/test-class-accredible-learndash-admin-action-handler.php
Labels: reviewed

#39 add get_row method to models and remove nonce verification for edit form
  includes/helpers/class-accredible-learndash-admin-table-helper.php
  includes/models/class-accredible-learndash-model.php
  includes/templates/admin-auto-issuance-form.php
  tests/includes/models/test-class-accredible-learndash-model-auto-issuance-log.php
  tests/includes/models/test-class-accredible-learndash-model-auto-issuance.php
Labels: reviewed

#40 NTGR-612: Update the order of the auto issuance logs
  includes/models/class-accredible-learndash-model.php
  includes/templates/admin-auto-issuance-logs.php
  tests/includes/models/test-class-accredible-learndash-model-auto-issuance-log.php
  tests/includes/models/test-class-accredible-learndash-model-auto-issuance.php
Labels: reviewed

#42 NTGR-620, NTGR-621 - ajax add/edit auto issuance
  assets/css/accredible-admin-settings.css
  assets/js/accredible-common.js
  assets/js/accredible-toast.js
  includes/ajax/class-accredible-learndash-ajax.php
  includes/class-accredible-learndash-admin-action-handler.php
  includes/class-accredible-learndash-admin.php
  includes/helpers/class-accredible-learndash-admin-table-helper.php
  includes/models/class-accredible-learndash-model-auto-issuance.php
  includes/models/class-accredible-learndash-model.php
  includes/templates/admin-auto-issuance-form.php
  tests/includes/models/test-class-accredible-learndash-model-auto-issuance.php
  tests/includes/test-class-accredible-learndash-admin-action-handler.php
Labels: reviewed

#43 Release/1.0.5
  accredible-learndash-add-on.php
  assets/css/accredible-admin-settings.css
  assets/js/accredible-common.js
  assets/js/accredible-toast.js
  includes/ajax/class-accredible-learndash-ajax.php
  includes/class-accredible-learndash-admin-action-handler.php
  includes/class-accredible-learndash-admin.php
  includes/helpers/class-accredible-learndash-admin-table-helper.php
  includes/models/class-accredible-learndash-model-auto-issuance.php
  includes/models/class-accredible-learndash-model.php
  includes/templates/admin-auto-issuance-form.php
  readme.txt
  tests/includes/models/test-class-accredible-learndash-model-auto-issuance.php
  tests/includes/test-class-accredible-learndash-admin-action-handler.php
Labels: waiting-review
